title: PRIYONO.ID
description: Selamat datang di situs web personal dari I V Agung EKo Priyono. Semoga informasi disini bermanfaat bagi kita semua.\nJourney to be Simple.

show_downloads: false

baseurl: "/" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://priyono.id" # change this to the base hostname & protocol for your site

plugins:
  - jekyll-mentions
  
permalink: pretty

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%-d %b %Y"

theme: # leave it empty

# social
author: "I V Agung Eko Priyono"
image: /thumbnail-jumbo.png
twitter:
  username: iv_agung_ep
#  site:
facebook:
  #publisher: 
  #profile_id: 
  app_id:  # cayman-blog
  #authors: iv.agung.ep
#  admins:
